version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      antora:
        patterns:
          - '@antora/*'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
