---
roosty_domain: roosty.example.com
roosty_acme_email: admin@example.com
roosty_image_tag: 0.1.0-alpha.2
roosty_instance_name: Roosty
roosty_instance_description: A Roosty instance
roosty_registration_mode: closed
roosty_elk_enabled: true
roosty_phanpy_enabled: false
roosty_federation_enabled: false
roosty_federation_allowed_domains: []
roosty_federation_blocked_domains: []
roosty_federation_delivery_max_age: 7d
roosty_worker_concurrency: 4
